[package]
name = "rest-db"
version = "0.1.0"
edition = "2021"

[dependencies]
heed = "0.21.0"
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
v8 = "134.2.0"
regex = "1.11.1"